{
 "title": "Host Metrics",
 "tags": [
  "eyeflow",
  "v2"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": { "query": "label_values(customer)" } },
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values({customer=~\"$customer\"},station)"
    }
   },
   { "name": "host", "label": "Host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Host Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[$host] Alert Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Alert Information",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Instant Host Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Customer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Station",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{station}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "OS Bits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_os_bit_lenght{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIC IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "selfip_present{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{ipaddr}}"
    }
   ]
  },
  {
   "title": "Last Heartbeat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(time() - station_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_uptime_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{station_uptime}}"
    }
   ]
  },
  {
   "title": "GPU Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_name_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{gpu_name}}"
    },
    {
     "expr": "jetson_name_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{jetson_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_memory{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_total_memory{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_architecture_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{station_architecture}}"
    }
   ]
  },
  {
   "title": "GPU CUDA Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_cuda_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{gpu_cuda}}"
    },
    {
     "expr": "jetson_cuda_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{jetson_cuda}}"
    }
   ]
  },
  {
   "title": "GPU Driver Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_driver_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{gpu_driver}}"
    },
    {
     "expr": "jetson_driver_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{jetson_driver}}"
    }
   ]
  },
  {
   "title": "CPU in use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - station_use_idle{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - ((station_mem_free{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} + station_mem_cached{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}) / station_mem_total{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cores{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU in use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "jetson_gpu_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "GPU Memory in use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((gpu_memory{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} - gpu_mem_free{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}) / gpu_memory{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cpu_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_temp_cpu{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Motherboard Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_mb_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_pci_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_temperature{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_temp_gpu{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_power{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_power{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}/1000 > 0"
    }
   ]
  },
  {
   "title": "Docker Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "docker_status{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "docker_status_age{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "docker_created{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Top OS Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "top_process_cpu{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "top_process_mem{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "top_process_pid{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "top_process_name_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "(Jetson) Sensor Profile",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "jetson_name_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_fan_pct{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_cpu_total{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jetson_nvp_model_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(x86) Host Sensors Profile",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "station_chassis_fan{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "station_cpu_fan{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "station_pci_power{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "station_cpu_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "station_mb_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "station_pci_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "(x86) GPU Profile",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "gpu_fan_percent{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_temp_max{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_temp_slow{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_temp_target{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_power_limit{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_power_max{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_temperature{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "gpu_power{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization over 20%",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "disk_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} >= 20"
    }
   ]
  },
  {
   "title": "Disk Profile",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 47 },
   "targets": [
    {
     "expr": "disk_read_req_persec{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_write_req_persec{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_read_await{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_write_await{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_read_req_queued_persec{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_write_req_queued_persec{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    },
    {
     "expr": "disk_avg_queue{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "[$host] NIC Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "nic_ip_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "NIC Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(nic_rx{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "-sum(nic_tx{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"})",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_mem_total{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "station_mem_used{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "station_mem_free{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "station_mem_cached{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  { "title": "Time Series Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Processing in Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - station_use_idle{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "CPU"
    },
    {
     "expr": "jetson_cpu_avg_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "JetsonCPU Average"
    },
    {
     "expr": "jetson_cpu_max_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "Jetson CPU Maximum"
    }
   ]
  },
  {
   "title": "Memory in Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((station_mem_free{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} + station_mem_cached{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}) / station_mem_total{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"})",
     "legendFormat": "Main"
    },
    {
     "expr": "gpu_mem_utilization{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} / gpu_memory{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "GPU Mem"
    }
   ]
  },
  {
   "title": "Host Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "station_cpu_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "station_pci_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "PCI"
    },
    {
     "expr": "station_mb_temp{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Motherboard"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "GPU"
    },
    {
     "expr": "jetson_temp_gpu{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"} > 0",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "API Get Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "api_get_status{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Network Connection Active",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ping_loss_pct{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Connect to {{ipaddr}}"
    }
   ]
  },
  {
   "title": "Self IP Match",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - selfip_present{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "Self IP: {{ipaddr}}"
    }
   ]
  },
  {
   "title": "Host Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - station_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "External Service Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - service_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Camera Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - camera_heartbeat{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Collector Exec Module Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "{__name__=~\"error_exec.+\", customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{mod}}"
    }
   ]
  },
  {
   "title": "Camera Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "camera_status{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{camera}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 9, "x": 9, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "agent_version_info{customer=~\"$customer\", station=~\"$station\", host=~\"$host\"}",
     "legendFormat": "{{agent_version}}"
    }
   ]
  }
 ]
}