global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'eyeflow-station'
rule_files:
  - 'alert.rules'
# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
scrape_configs:
  - job_name: 'stations'
    scrape_interval: 10s
    static_configs:
      - targets: [192.168.2.2:9089,
                  192.168.2.3:9089,
                  192.168.2.4:9089,
                  192.168.2.5:9089]
                  
