global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'eyeflow-station'
rule_files:
  - 'alert.rules'
# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 10s
    dns_sd_configs:
    - names:
      - 'tasks.pushgateway'
      type: 'A'
      port: 9091
