server:
  http_listen_address: 127.0.0.1
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /opt/eyeflow/monitor/promtail/positions/positions.yaml
clients:
  - url: 
scrape_configs:
  - job_name: eyeflow_logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: eyeflow
        __path__: /opt/eyeflow/log/*log
        customer: 
        station: 
        host: 
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
        customer: 
        station: 
        host: 
  - job_name: monitor
    static_configs:
    - targets:
        - localhost
      labels:
        job: metric-collector
        __path__: /opt/eyeflow/monitor/*log
        customer: 
        station: 
        host: 
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        customer: 
        station: 
        host: 
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: docker
    entry_parser: raw
    static_configs:
    - targets:
        - localhost
      labels:
        customer: 
        station: 
        host: 
        job: docker
        __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag
    - regex:
        expression: (?P<container_name>(?:[^|]*[^|]))
        source: "tag"
    - labels:
        stream:
        container_name:
