route:
  receiver: 'ms-teams'
  group_by: ['alertname']
  group_interval: 1m
  repeat_interval: 30m
  group_wait: 10s
  continue: true

receivers:
  - name: 'ms-teams'
    webhook_configs:
    - url: "http://alertapi:2000/alertmanager"
      send_resolved: true
 